# Generated by Django 2.2.3 on 2019-09-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_venue_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_role',
            field=models.CharField(choices=[('C', 'Customer'), ('M', 'Manager')], default='C', max_length=1),
        ),
    ]
