# Generated by Django 2.2.3 on 2019-09-18 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20190918_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bought_tickets',
        ),
    ]
