# Generated by Django 2.2.3 on 2019-09-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_profile_bought_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='total_tickets',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
